version: '3'
services:
  mongodb:
    image: demo-database
    container_name: database
    ports:
      - '27017:27017'
    volumes:
      - '/home/danielmillson/Documents/Projects/Git Projects/MicroservicesDemo/Orchestration:/Demo/Database:rw'
    networks:
      - demo-micro
  crud-service:
    image: demo-crud
    container_name: crud
    ports:
      - '3000:3000'
    volumes:
      - '/home/danielmillson/Documents/Projects/Git Projects/MicroservicesDemo/CRUD:/Demo/CRUD:rw'
    networks:
      - demo-micro
  orchestration:
    image: demo-orchestration
    container_name: orc
    ports:
      - '3001:3001'
    volumes:
      - '/home/danielmillson/Documents/Projects/Git Projects/MicroservicesDemo/Orchestration:/Demo/Orchestration:rw'
    networks:
      - demo-micro
  # frontend:
  #   image: demo-frontend
  #   container_name: frontend
  #   ports:
  #     - '4200:4200'

networks:
  demo-micro:
    external: false
