version: '3'
services:
  mongodb:
    image: demo-database
    container_name: demo-database
    ports:
      - '27017:27017'
    volumes:
      - '/home/danielmillson/Documents/Projects/Git Projects/MicroservicesDemo/Orchestration:/Demo/Database:rw'
    network_mode: 'host'
  crud-service:
    image: demo-crud
    container_name: demo-crud
    ports:
      - '3000:3000'
    volumes:
      - '/home/danielmillson/Documents/Projects/Git Projects/MicroservicesDemo/CRUD:/Demo/CRUD:rw'
    network_mode: 'host'
  orchestration:
    image: demo-orchestration
    container_name: demo-orchestration
    ports:
      - '3001:3001'
    volumes:
      - '/home/danielmillson/Documents/Projects/Git Projects/MicroservicesDemo/Orchestration:/Demo/Orchestration:rw'
    network_mode: 'host'
  frontend:
    image: demo-frontend
    container_name: demo-frontend
    ports:
      - '4200:4200'
    network_mode: 'host'

networks:
  demo-micro:
    external: false
